version: '3.9'

volumes:
  postgres_data:

networks:
  main:
    name: main_network
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - main
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - VITE_AUTH0_DOMAIN=dev-4tze8y46hhx3kohe.us.auth0.com
      - VITE_AUTH0_CLIENT_ID=6AxtuOgBlRVhv9jVmLNyjbPYV0rb58Xt
      - VITE_AUTH0_CALLBACK_URL=http://localhost:3000/callback
      - VITE_API_SERVER_URL=http://localhost:5000

    # depends_on:
    #   - db
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=flaskr/app.py:create_app()
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - JWT_SECRET_KEY=SuperSecret
      # - DATABASE_URL=postgresql://postgres:postgrespw@db:5432/postgres
      # - DATABASE_URL=postgresql://postgres:postgrespw@test-gamenight-db.c9wkwugm84s6.us-east-2.rds.amazonaws.com:5432/test-gamenight-db
      - CLIENT_ORIGIN_URL=http://localhost:3000
      - AUTH0_AUDIENCE=Flask-Backend-API
      - AUTH0_DOMAIN=dev-4tze8y46hhx3kohe.us.auth0.com
    networks:
      - main
    # depends_on:
    #   - db

  # db:
  #   container_name: database
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USERNAME=postgres
  #     - POSTGRES_PASSWORD=postgrespw
  #   networks:
  #     - main
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: matthewjcorbett96@gmail.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    networks:
      - main
    ports:
      - 5050:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin  # Persist PgAdmin data
    user: "5050:5050"
    # depends_on:
    #   - db

  
