version: '3.9'

volumes:
  postgres_data:

networks:
  main:
    name: main_network
    driver: bridge

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile-Dev-Backend
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    networks:
      - main
    depends_on:
      - db
      - redis
    
  celery:
    container_name: worker
    build:
      context: ./backend
    networks:
      - main
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: celery -A flaskr.run.celery worker -B --loglevel=info
    depends_on:
      - redis
      - backend
      - db

  db:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgrespw
    networks:
      - main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: matthewjcorbett96@gmail.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    networks:
      - main
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin  # Persist PgAdmin data
    user: "5050:5050"
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - main
    ports:
      - "6379:6379"

  
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile-Dev-Frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   networks:
  #     - main
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - NODE_ENV=development
  #     - VITE_AUTH0_DOMAIN=dev-4tze8y46hhx3kohe.us.auth0.com
  #     - VITE_AUTH0_CLIENT_ID=6AxtuOgBlRVhv9jVmLNyjbPYV0rb58Xt
  #     - VITE_AUTH0_CALLBACK_URL=http://localhost:3000/callback
  #     - VITE_API_SERVER_URL=http://localhost:5000

  #   depends_on:
  #     - db
  