volumes:
  data: {}

services:
  myapp:
    image: gamenightproject:a0.1
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports: 
      - 8080:8080
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=matthewjcorbett96@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_ADDRESS=pgadmin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:8081
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USERNAME=postgres
    ports:
      - 6060:8082
    volumes:
      - data:/var/lib/postgresql