"""empty message

Revision ID: 318ca2dd7267
Revises: e1e469dfcef3
Create Date: 2023-07-07 19:41:43.011786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '318ca2dd7267'
down_revision = 'e1e469dfcef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('game_night_games', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('game_nights', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    with op.batch_alter_table('game_nights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    with op.batch_alter_table('game_night_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
