"""Adding Auth0 for Users

Revision ID: 58d89f44f246
Revises: 62c7a4e9c0db
Create Date: 2023-10-22 03:02:50.103635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d89f44f246'
down_revision = '62c7a4e9c0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_auth0_id'), ['auth0_id'], unique=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_auth0_id'))
        batch_op.drop_column('auth0_id')

    # ### end Alembic commands ###
