"""empty message

Revision ID: 8a375f533530
Revises: 318ca2dd7267
Create Date: 2023-07-07 19:42:54.290229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a375f533530'
down_revision = '318ca2dd7267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('game_night_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('game_nights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('game_nights', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('game_night_games', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    # ### end Alembic commands ###
