"""empty message

Revision ID: baa8e7b1ede1
Revises: 70c76f4e4b7b
Create Date: 2024-02-24 21:34:29.697740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'baa8e7b1ede1'
down_revision = '70c76f4e4b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round_winners')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round_winners',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('round_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name='round_winners_round_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='round_winners_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'round_id', 'id', name='round_winners_pkey'),
    sa.UniqueConstraint('id', name='round_winners_id_key')
    )
    # ### end Alembic commands ###
