"""empty message

Revision ID: e1e469dfcef3
Revises: 
Create Date: 2023-07-07 19:08:52.548070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e469dfcef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('game_night_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('game_nights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    with op.batch_alter_table('game_nights', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    with op.batch_alter_table('game_night_games', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
