# build image and push to aws ecr with tag backend:latest
name: Build and Push Docker Image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: arn:aws:iam::211125573631:user/Matthew-Corbett
        aws-region: aws-region-1
    - name: Build and Push Docker Image
      uses: aws-actions/amazon-ecr-login@v2
      with:
          registries: f5d8h7v1  # Assuming 'f5d8h7v1' is your registry ID, and it's placed in an array if necessary
          region: us-east-1
          mask-password: true
          registry-type: public
          skip-logout: false
# Path: .github/workflows/main.yaml


