# build image and push to aws ecr with tag backend:latest
name: Build and Push Docker Image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Push Docker Image
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: f5d8h7v1
        region: us-east-1
        mask-password: true
        registry-type: public
    - name: Build Docker Image
      run: docker build -t f5d8h7v1/game-night-ecr:backend ./backend --file DockerFile
    - name: Push Docker Image
      run: docker push f5d8h7v1/game-night-ecr:backend

# Path: .github/workflows/main.yaml


